import { VerticalBox , Button, AboutSlint } from "std-widgets.slint";
export component AppWindow {
    VerticalBox {
        AboutSlint {}
        rect:= Rectangle {
            height: 100px;
            background: btn.pressed ? green : red;
            Text {
                text: "Hello World";
                font-size: 18px;
                horizontal-alignment: center;
            }
        }
        btn:= Button { 
            height: 100px;
            text: "Press me!";
         }
    }
    
}
